### PR TITLE
III-3570 udb3-models value object adapters

### PR DESCRIPTION
**Pull request by bertramakers**
### Added
 
- Added factory method to create a `Status` from an udb3-models `Status`
 
### Changed
 
- Changed factory method on `Timestamp` to also include an `Status` when converting an udb3-models `DateRange` to a `Timestamp`
  
---
Ticket: https://jira.uitdatabank.be/browse/III-3570

Todo:
- [x] https://github.com/cultuurnet/udb3-models/pull/11 should be merged first and a ~`1.1.0`~ `2.0.0` release should be made so we can remove the composer dependency on a feature branch
- [x] Some changes will have to be made to make this work with the recent refactoring in udb3-models to rename EventStatus to Status and use the correct enum values etc.
- [x] Tests

Note: The reason we need these conversions is because right now the JSON-LD imports in `udb3-silex` use `udb3-models` to validate and deserialize the incoming JSON-LD, which has its own value objects because it's a standalone package, but we need the udb3-php value objects to include in the commands to dispatch to the command bus.

In theory these two PRs should be sufficient to add support for `eventStatus` in the imports, because the `EventDocumentImporter` in udb3-silex already dispatches an `UpdateCalendar` command. The only thing that was missing was a way to include the `eventStatus` and `eventStatusReason` in the `Calendar` object inside that dispatched command. https://github.com/cultuurnet/udb3-silex/blob/master/src/Model/Import/Event/EventDocumentImporter.php#L160

### CODE REVIEW

**Comment by bertramakers** [comment]
Some changes will need to be made in https://github.com/cultuurnet/udb3-models/pull/11 first based on new insights, and then this will need to be updated to be compatible with those changes.

**Comment by jdrieghe** [comment]
@bertramakers This should be ready to accept the update naming from `udb3-models` when it's finished

**Comment by bertramakers** [comment]
Super, thanks for the help by preparing this already! 👏

**Comment by bertramakers** [comment]
Looks good to me, but I can't approve it since it's my own PR. Can you approve it @jdrieghe?

In the meantime I'll pull this branch into my local copy of `udb3-silex` and make sure everything works as expected. If not we can still do the necessary fixes in this PR.

**Comment by bertramakers** [comment]
I found a bug in the conversion of `Status` objects from `udb3-model` to `udb3-php`.
Fixed it and added a test for it.

I also noticed that the `StatusReason` class in `udb3-php` used a `Language` value-object from `udb3-model`. To keep the two a bit better separated for now I refactored that to use the `udb3-php` `Language` class.

I know it's a bit confusing having these duplicates and I hope we can simplify that once we can merge these two packages into `udb3-silex`. For now I just believe it's best to keep them as separate as possible, aside from these factory methods to convert them, so it doesn't become an even bigger spaghetti than it already is.

**Review by jdrieghe — APPROVED** [review]

**Pull request merged**
