### PR TITLE
III-3047 - Always use canonical place when creating or updating an event

### PR DESCRIPTION
**Pull request by jdrieghe**
### Added
- Process manager to update locations to canonical places for events that were created or updated to use a place that was marked as a duplicate before

---
Ticket: https://jira.uitdatabank.be/browse/III-3047

### CODE REVIEW

**Comment by jdrieghe** [comment]
Note that this still needs service provisioning in `cultuurnet/udb3-silex`

**Comment by bertramakers** [comment]
> Note that this still needs service provisioning in `cultuurnet/udb3-silex`

Are you going to do that in scope of this ticket when this is merged? If not, can you create a new ticket for it?

**Comment by jdrieghe** [comment]
@bertramakers I'll tackle it in the scope of this ticket. Creating a new PR for it as we speak.

**Comment by jdrieghe** [comment]
It's just a lot easier to create that PR when this branch is merged.

**Pull request merged**
